accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from accounts.views import UserDetailView, ChangePasswordView

_urlpatterns = [
    url('^$', 'accounts.views.index', name='index'),
    url('^login/$', RedirectView.as_view(pattern_name='account:index'), 
        name='login'),
    url('^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, 
        name='logout'), 
    url('^register/$', 'accounts.views.register', name='register'),
    url('^edit/$', UserDetailView.as_view(), name='edit'),
    url('^forgot/$', 'accounts.views.forgot', name='forgot_password'),
    url('^forgot/(?P<code>[a-f0-9]{32})$', 'accounts.views.forgot_reset', 
        name='forgot_reset'),
    url('^confirm-account/$', 'accounts.views.social_confirm',
        name='social_confirm'),
    url('^verify_new_email$', 'accounts.views.verify_new_email',
        name='verify_new_email'),
    url('^verify/(?P<code>[a-f0-9]{32})$', 'accounts.views.verify_email', 
        name='verify_email'),
    url('^change-password/$', ChangePasswordView.as_view(),
        name='change_password'),
]


if settings.DEBUG:
    _urlpatterns.extend([
        url('^promote-user$', 'accounts.views.promote_user'),
        url('^debug$', 'accounts.views.debug_page')
    ])


def urls(namespace='account'):
    """Returns a 3-tuple for use with include().

    The including module or project can refer to urls as namespace:urlname,
    internally, they are referred to as app_name:urlname.
    """
    return (_urlpatterns, 'account', namespace)

accounts/templates/accounts/forgot/forgot.html
{% extends "base.html" %}

{% block content %}

<script>
</script>

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    <h3 style="text-align: center;">To recover your password, please enter your email address</h3>
    <div>
        <form class="login-form" method="POST" action="{% url 'account:forgot_password' %}">
            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto; 
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i { 
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
            {% csrf_token %}
            
            <hr />
            {{ form.as_div }}
            <hr />
            <div style="text-align: center; margin: 0 auto; width: 50%">
                <button class="btn btn-success" onclick='javascript:this.form.submit()'>Send Reset Email &rarr;</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/forgot/reset.html
{% extends "base.html" %}

{% block content %}

<script>
</script>

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    <h3 style="text-align: center;">Please choose a new password</h3>
    <div>
        <form class="login-form" method="POST" action="{% url 'account:forgot_reset' code %}">
            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto; 
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i { 
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
            {% csrf_token %}
            
            <hr />
            {{ form.as_div }}
            <hr />
            <div style="text-align: center; margin: 0 auto; width: 50%">
                <button onclick='javascript:this.form.submit()'>Change Password &rarr;</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/forgot/reset_successful.html
{% extends "base.html" %}

{% block content %}

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    <h3 style="text-align: center;">Password reset successful.</h3>
    <div>
        <p>You may now <a href="{% url 'account:login' %}">Log in</a>.</p>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/forgot/wait_for_email.html
{% extends "base.html" %}

{% block content %}

<script>
</script>

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    <h3 style="text-align: center;">Check your email.</h3>
    <div>
        <p>If you have an account registered on our system, you will receive 
            an email with reset instructions in a few minutes.</p>
            
    </div>
</div>


{% endblock %}