accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from accounts.views import UserDetailView, ChangePasswordView

_urlpatterns = [
    url('^$', 'accounts.views.index', name='index'),
    url('^login/$', RedirectView.as_view(pattern_name='account:index'), 
        name='login'),
    url('^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, 
        name='logout'), 
    url('^register/$', 'accounts.views.register', name='register'),
    url('^edit/$', UserDetailView.as_view(), name='edit'),
    url('^forgot/$', 'accounts.views.forgot', name='forgot_password'),
    url('^forgot/(?P<code>[a-f0-9]{32})$', 'accounts.views.forgot_reset', 
        name='forgot_reset'),
    url('^confirm-account/$', 'accounts.views.social_confirm',
        name='social_confirm'),
    url('^verify_new_email$', 'accounts.views.verify_new_email',
        name='verify_new_email'),
    url('^verify/(?P<code>[a-f0-9]{32})$', 'accounts.views.verify_email', 
        name='verify_email'),
    url('^change-password/$', ChangePasswordView.as_view(),
        name='change_password'),
]


if settings.DEBUG:
    _urlpatterns.extend([
        url('^promote-user$', 'accounts.views.promote_user'),
        url('^debug$', 'accounts.views.debug_page')
    ])


def urls(namespace='account'):
    """Returns a 3-tuple for use with include().

    The including module or project can refer to urls as namespace:urlname,
    internally, they are referred to as app_name:urlname.
    """
    return (_urlpatterns, 'account', namespace)

accounts/templates/accounts/change_password_form.html
{% extends "base.html" %}

{% block content %}

<script>
</script>

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    <h2 style="text-align: center;">Hello, {{ user.get_short_name }}</h2>
    <h3 style="text-align: center;">Use this form to change your password.</h3>
    <div>
        <form class="login-form" method="POST" action="{% url 'account:change_password' %}">
            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto; 
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i { 
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
            {% csrf_token %}
            
            <hr />
            {{ form.as_div }}
            <hr />
        <div style="text-align: center; margin: 0 auto; width: 50%">
            <button class="btn btn-success" onclick='javascript:this.form.submit()'>Change Password &rarr;</button>
            <br />
            <br />
            <a href="{% url 'account:index' %}">I changed my mind</a>
            </form>
        </div>
        </form>
            
            
    </div>

</div>


{% endblock %}

accounts/templates/accounts/check_your_email.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div style="border: 1px solid blue; margin: 1em 1em; padding: 1em; display: block; margin-right: auto; margin-left: auto; width: 65%; margin-bottom: 50px;">
    <h4 style="text-align: center;">Check your email for a verification link to continue registration. </h4>
</div>

{% load welcome_entry %}
{% welcome_entry %}
{% endblock %}

accounts/templates/accounts/debug.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Account debug page</h1>

<div>
    <style>
        dt {
            float:left;
            clear:left;
            text-align: right;
            width: 120px;
        }
        dt:after {
            content: ": ";
        }
        dd {
            margin: 0 0 0 125px;
            padding: 0 0 0 0;
        }

    </style>
    All Users:<br />
    <ol>
    {% for u in users %}
        <li>
            <dl>
                <dt>preferred name</dt><dd>&ldquo;{{ u.get_short_name }}&rdquo; (id={{u.pk}})</dd>
                <dt>name</dt><dd>&ldquo;{{ u.get_full_name }}&rdquo;</dd>
                <dt>email</dt>
                    <dd>{{ u.email }}</dd>
                <dt>auth provider</dt>
                    <dd>{% for provider in u.social_auth.all %}{{ provider.provider }}{% empty %}django{% endfor %}</dd>
            </dl>
        </li>
    {% endfor %}
    </ol>
    <hr/>
    Active sessions:<br/>
    {% for session in sessions %}
    {{ session.user }} until {{ session.until|date:"r" }}<br />
    {% empty %}
    No active sessions<br/>
    {% endfor %}
</div>

</body>
</html>

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block content %}

<div class="mapgroup">
    <!-- left column - profile image -->
    <div class="col-md-1">
        <div style="height: 66px; width: 66px; border-radius: 32px;
        border: 0 solid black;
        overflow: hidden;
        position: absolute; top: 3px; right: 16px;
        background: url({{ user.userdata.profile_image }}) no-repeat center center;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;">
        </div>
    </div>
    <div class="col-md-8">
        <h1 style="margin-top: 0; width: initial; border-left: 1px solid #b1b3b5; margin-left: -12px; padding-left: 12px">Hello, {{ user.first_name }}. </h1>
        <p><!-- user description --> </p>

        <h3>Profile Information</h3>
        <p>Name: {{ user.get_full_name }}</p>
        <p>Preferred Name: {{ user.get_short_name }}</p>
        <p>email: {{ user.email|default:"<i style='color:red'>No Email Address</i>" }}</p>
        <p>
        <a class="btn btn-success" href="{% url 'account:edit' %}">Edit my info</a>
        {% if can_change_password %}
        <a class="btn btn-success" href="{% url 'account:change_password' %}">Change my password</a>
        {% endif %}
        </p>
        <p>
        {% if user.is_superuser %}
            <a class="btn btn-success" href="/django-admin">Go to the Django admin page</a>
        {% endif %}
        {% if user.is_staff %}
            <a class="btn btn-success" href="/admin">Go to the CMS admin page</a>
        {% endif %}
        </p>

        {% if not user.userdata.email_verified %}
        <blockquote class="warn" style="border-left-color: #ea3a54; background-color: #eee">
            <p>Your email address has not been verified. </p>
            <p>Please verify your email address to complete your registration.</p>
            <form style="display:inline;" method="POST" action="{% url 'account:verify_new_email' %}">{% csrf_token %}
                <button class='btn btn-success' onclick="this.form.submit()">Verify email</button>
            </form>
        </blockquote>
        {% endif %}


        <h3>Map Groups</h3>
        <ul style="padding-left: 0">
            {% for membership in request.user.mapgroupmember_set.all %}
            <li style="float:left; width: 150px; height: 120px; text-align: center; list-style-type: none; margin-left: 0">
                 <a href="{{ membership.map_group.get_absolute_url }}">
                     <img src="{{ membership.map_group.image_url }}" width="124" height="70" style="margin-bottom: 1em;"><br>
                     {{ membership.map_group.name }}
                 </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-3">
        <a class="btn btn-success" href="{% url 'account:logout' %}">Log out</a><br />
    </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'accounts/accounts.scss' %}" />
{% endblock %}

{% block content %}
<div class="login">
    
    <h2>Log in.</h2>
    
    <p>Anyone can join the MARCO Portal&mdash;<a href="{% url 'account:register' %}">becoming a member</a> allows you 
    to join and create interest groups, custom data layers, and share 
    map views with your collaborators.</p>

    <div>
        <br />
        <br />
        <form class="login-form" method="POST" action="{% url 'account:index' %}{% if next %}?next={{ next }}{% endif %}">
                {% csrf_token %}

                {{ form.as_div }}


            <div class="social-login">
                or log in with
                <a class="fa-stack fa-lg" href="{% url 'social:begin' 'twitter' %}?next={{ next }}">
                    <i class="fa fa-circle fa-stack-2x green"></i>
                    <i class="fa fa-twitter fa-stack-1x white"></i>
                </a>

                <a class="fa-stack fa-lg" href="{% url 'social:begin' 'facebook' %}?next={{ next }}">
                    <i class="fa fa-circle fa-stack-2x green"></i>
                    <i class="fa fa-facebook fa-stack-1x white"></i>
                </a>
            </div>

            <div class="text-center">
                <button class="btn btn-success btn-lg" onclick='this.form.submit()'>Log in &rarr;</button>
            </div>
        </form>
    </div>

    <div>
        <br />
        <br />
        <p class="text-center">
            <a href="{% url 'account:forgot_password' %}">I forgot my password</a>
            &bull; <a href="{% url 'account:register' %}">I want to register</a>
            &bull; <a href="/help/">Help</a>
        </p>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load welcome_entry static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'accounts/accounts.scss' %}" />
{% endblock %}

{% block content %}
{% welcome_entry %}

<div style="border: 1px solid #22408f; margin: 1em 10em; padding: 0 3em ">
    <h2 id="form-begin" style="text-align: center;">Sign Up</h2>

    <div class="login-form">
        <div><h4>Sign up with your Facebook or Twitter account</h4></div>
        <div class="social-login" style="text-align:center">
            <a class="fa-stack fa-lg" href="{% url 'social:begin' 'twitter' %}?next={{ next }}">
                <i class="fa fa-circle fa-stack-2x green"></i>
                <i class="fa fa-twitter fa-stack-1x white"></i>
            </a>

            <a class="fa-stack fa-lg" href="{% url 'social:begin' 'facebook' %}?next={{ next }}">
                <i class="fa fa-circle fa-stack-2x green"></i>
                <i class="fa fa-facebook fa-stack-1x white"></i>
            </a>
        </div>
    </div>
    <div>
        <form class="login-form" id="register-form" method="POST" action="{% url 'account:register' %}#form-begin">
            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto; 
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i { 
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
            {% csrf_token %}
            
            <hr style="border-color: #b1b3b5" />
            <div>
                <h4>Or create a new account with a password</h4>
            </div>

            {{ form.as_div }}
            <hr style="border-color: #b1b3b5" />

            <div style="text-align: center;">
                <button class='btn btn-success' onclick='this.form.submit()'>Sign up &rarr;</button>
            </div>
        </form>
    </div>

    <p style="text-align: center">
        <a href="{% url 'account:forgot_password' %}">I forgot my password</a>
         &bull; <a href="/help/">Help</a>
    </p>

</div>

{% endblock %}

accounts/templates/accounts/registration_error.html
{% extends "base.html" %}


{% block content %}
<div style="padding-top: 4em">
	<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
	    <h3 style="text-align: center;">Your user account was not successfully created.</h3>
	    <h5 style="text-align: center;">A user may already exist. <a href="{% url 'account:register' %}">Please try registering again. </a></h5>
	</div>
</div>


{% endblock %}

accounts/templates/accounts/social_confirm.html
{% extends "base.html" %}

{% block content %}

<script>
</script>

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    {% if user_first_name %}<h2 style="text-align: center;">Hello, {{ user_first_name }}</h2>{% endif %}
    <h3 style="text-align: center;">Please confirm your account details.</h3>
    <div>
        <form class="login-form" method="POST" action="{% url 'account:social_confirm' %}">
            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto; 
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i { 
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
            {% csrf_token %}
            
            <hr />
            {{ form.as_div }}
            <hr />
        <div style="text-align: center; margin: 0 auto; width: 50%">
            <button onclick='javascript:this.form.submit()'>Finish &rarr;</button>
            <br />
            <br />
            {% comment %}
            Below is the official way to cancel a registration process, however,
            doing so carries a bad ?next redirect value to the next page. 
            
            It *also* leaves partial pipeline data floating around in the 
            session, leading to registration oddness (MP-694).
            {% endcomment %}
            <a href="{% url 'social:disconnect' backend %}">I changed my mind</a>
            </form>
        </div>
        </form>
            
            
    </div>

</div>


{% endblock %}

accounts/templates/accounts/user_detail_form.html
{% extends "base.html" %}

{% block content %}

<script>
</script>

<div style="border: 1px solid blue; margin: 1em 10em; padding: 3em">
    <h2 style="text-align: center;">Hello, {{ user.get_short_name }}</h2>
    <h3 style="text-align: center;">Update your account details.</h3>
    <div>
        <form class="login-form" method="POST" action="{% url 'account:edit' %}">
            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto; 
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i { 
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
            {% csrf_token %}
            
            <hr />
            {{ form.as_div }}
            <hr />
        <div style="text-align: center; margin: 0 auto; width: 50%">
            <button onclick='javascript:this.form.submit()'>Finish &rarr;</button>
            <br />
            <br />
            <a href="{% url 'account:index' %}">I changed my mind</a>
            </form>
        </div>
        </form>
            
            
    </div>

</div>


{% endblock %}

accounts/templates/accounts/verify_email_success.html
{% extends "base.html" %}

{% block content %}

	<div style="border: 1px solid blue; margin: 1em 1em; padding: 1em; display: block; margin-right: auto; margin-left: auto; width: 55%; margin-bottom: 50px;">
		<h4 style="text-align: center;">Your email has been verified successfully.</h4>
		<h5 style="text-align: center;">You may now <a href="{% url 'account:index' %}">Log In</a>.</h5>
	</div>

{% load welcome_entry %}
{% welcome_entry %}

{% endblock %}